// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7OK4AbP2dkYL-6DZ1J29uXNt8A01IXbA',
    appId: '1:112554834425:web:9a2d8267f39ddeee8ba528',
    messagingSenderId: '112554834425',
    projectId: 'canhearenglish',
    authDomain: 'canhearenglish.firebaseapp.com',
    storageBucket: 'canhearenglish.appspot.com',
    measurementId: 'G-6BXQTVB9N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFW-RJeiBPhwd2n2aBToREV367lCof7CY',
    appId: '1:112554834425:android:9ff92d833cbafb448ba528',
    messagingSenderId: '112554834425',
    projectId: 'canhearenglish',
    storageBucket: 'canhearenglish.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL80V7qRH01OIbn3R99cwHNiYcFuoh1x0',
    appId: '1:112554834425:ios:d250581dcc7450db8ba528',
    messagingSenderId: '112554834425',
    projectId: 'canhearenglish',
    storageBucket: 'canhearenglish.appspot.com',
    androidClientId: '112554834425-06esqofke21htm73r8t0rv1ft21andsj.apps.googleusercontent.com',
    iosClientId: '112554834425-ri7m0d354pvjtjkour9tgf9iv496387e.apps.googleusercontent.com',
    iosBundleId: 'com.shimnsso.ellasNotesFlutter',
  );
}
